template = "https://github.com/giellalt/template-lang-und"
rev_id = 274
template_sha = "43a0f0c0afaa856365e2bf3d3cb7eae06d27cc4d"

[replacements]
__GLOTTOLOG_ID__ = "klin1234"
__REPO__ = "lang-tlh"
__UND2C__ = "tlh"
__UNDEFINED__ = "Klingon"
__UND__ = "tlh"
