template = "https://github.com/giellalt/template-lang-und"
rev_id = 275
template_sha = "ae7f0a90eca4365746c3ec57f8e39437abd6d807"

[replacements]
__GLOTTOLOG_ID__ = "klin1234"
__REPO__ = "lang-tlh"
__UND2C__ = "tlh"
__UNDEFINED__ = "Klingon"
__UND__ = "tlh"
